l_german:
 SETTING_AUTOSAVE:0 "Autospeicherungs-Intervall"
 SETTING_DEBUG_SAVES:0 "Anzahl an Debug-Saves"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "Deaktivierte Tipps"
 SETTING_FOCUS_ON_COMBAT:0 "Fokus auf den Kampf"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "Reichsgrenzen an Küsten"
 SETTING_TOOLTIP_DELAY:1 "Tooltip-Verzögerung"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, bis Tooltips erscheinen."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Freischaltungsverzögerung"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips freigeschaltet werden."
 SETTING_TOOLTIP_LOCK_TIME:0 "Verriegelungsverzögerung"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Geöffnet-Geschlossen-Verögerung"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden, während ein anderer Tooltip geöffnet ist."
 # Audio
 SETTING_Sound_Effects:1 "Alle Soundeffekte"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Soundeffekte-Lautstärke\n#!Legt die Lautstärke aller Soundeffekte fest."
 SETTING_Ambience:0 "Atmo"
 SETTING_Ambience_TOOLTIP:1 "#T Atmo-Lautstärke\n#!Legt die Lautstärke der Umgebungs-Atmo fest."
 SETTING_TOOLTIP_MODE:1 "Tooltip-Modus"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nLegt fest, wie Tooltips „einrasten“ und erlaubt so Tooltips innerhalb von Tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Maustendenz"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips rasten automatisch an Ort und Stelle ein, bis sich der Mauszeiger wegbewegt."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Aktions-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nBenutzt die #V Mittlere Maustaste#!, um Tooltips ein- und ausrasten zu lassen."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips bleiben an Ort und Stelle eingerastet, solange sich der Mauszeiger eine kleine Weile nicht bewegt. #weak (Standardeinstellung.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Diverses"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Tooltips"
 SETTINGS_CATEGORY_SFX:0 "Spezifische Soundeffekte"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Allgemein"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Kartensteuerung"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Spielstände"
 SETTINGS_CATEGORY_LANGUAGE:0 "Sprache"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Fortgeschritten"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Porträts"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Verletzungen und Krankheiten darstellen"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nLegt fest, ob deutliche Verletzungen und Krankheiten bei Charakterporträts dargestellt werden."
 NEVER:0 "Nie"
 MONTHLY:0 "Jeden Monat"
 HALFYEAR:0 "Alle 6 Monate"
 YEARLY:0 "Jedes Jahr"
 FIVE_YEAR:0 "Alle 5 Jahre"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Reaktive Ratschläge anzeigen"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nLegt fest, ob das Spiel Ratschläge im Stil eines Tutorials in Reaktion auf Euer Handeln gibt. Nützlich für Spieler, die neu bei Crusader Kings III sind."
 SETTING_SHOW_SUGGESTIONS:0 "Vorschläge anzeigen"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nLegt fest, ob das Spiel in gewissen Abständen Vorschläge machen soll. Nützlich für Spieler, die neu bei Crusader Kings III sind."
 RESET_REACTIVE_ADVICE:0 "Reaktive Ratschläge zurücksetzen"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Reaktive Ratschläge zurücksetzen#!\nSchon gesehene Reaktive Ratschläge tauchen nur einmal auf."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Reaktive Ratschläge zurücksetzen"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Bist du sicher, dass du die reaktiven Ratschläge zurücksetzen willst?"
 SETTING_ADVANCED_SHADERS:0 "Advanced-Shader-Effekte"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Advanced-Shader-Effekte\n#!Diese Option aktiviert Advanced-Shader-Effekte.\n\nDas Abschalten kann die Leistung verbessern. Manche Effekte (beispielsweise Gelände und Wasser) können allerdings schlechter aussehen."
 BASED_ON_ZOOM_LEVEL:0 "Dynamisch"
 ALWAYS_HIDE:0 "Immer verbergen"
 ALWAYS_SHOW:0 "Immer anzeigen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Küstengrenzen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nDiese Option steuert, wann Reichsgrenzen an den Küsten angezeigt werden sollen.\nBei „$BASED_ON_ZOOM_LEVEL$“ werden sie auf der Detail-Zoom-Stufe verborgen.\n\nBei der Auswahl von „$ALWAYS_SHOW$“ oder „$ALWAYS_HIDE$“ kann die Leistung ein wenig verbessert werden, auf Kosten der fehlenden Grenzen an Küsten."
 
