l_simp_chinese:
 SETTING_AUTOSAVE:0 "自动保存间隔"
 SETTING_DEBUG_SAVES:0 "调试存档数量"
 SETTING_TUTORIAL:0 "教程"
 SETTING_DISABLED_HINTS:0 "关闭提示"
 SETTING_FOCUS_ON_COMBAT:0 "聚焦于战斗"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "海岸显示领地边境"
 SETTING_TOOLTIP_DELAY:0 "工具提示延迟"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_TOOLTIP_DELAY$#!\n设置工具提示出现之前的延时。"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "解锁延时"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n设置工具提示解锁之前的延时。"
 SETTING_TOOLTIP_LOCK_TIME:0 "锁定延时"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n设置工具提示锁定之前的延时。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "已开启时的锁定延时"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n设置已打开另一工具提示时，工具提示锁定之前的延时。"
 # Audio
 SETTING_Sound_Effects:0 "所有音效"
 SETTING_Sound_Effects_TOOLTIP:0 "#T 音效音量\n#!设定所有音效的音量。"
 SETTING_Ambience:0 "环境音效"
 SETTING_Ambience_TOOLTIP:0 "#T 环境音效音量\n#!设定环境音效音量。"
 SETTING_TOOLTIP_MODE:0 "工具提示模式"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE$#!\n设置工具提示“锁定”的方式，启用工具提示中的工具提示。"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "鼠标趋势"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\n工具提示自动锁定直到光标移开。"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "动作锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n按下#V 鼠标中键#!以锁定和解锁工具提示。"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "定时器锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\n如果光标短时间内不移动，则工具提示锁定。#weak （默认设置。）#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "杂项"
 SETTINGS_CATEGORY_TOOLTIPS:0 "工具提示"
 SETTINGS_CATEGORY_SFX:0 "特殊音效"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "通用"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "地图控制"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "保存游戏"
 SETTINGS_CATEGORY_LANGUAGE:0 "语言"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "高级"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "肖像"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "显示外伤与体表症状"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n设置是否在角色肖像上显示外伤与体表症状。"
 NEVER:0 "从不"
 MONTHLY:0 "每月"
 HALFYEAR:0 "每六个月"
 YEARLY:0 "每年"
 FIVE_YEAR:0 "每五年"
 SETTINGS_CATEGORY_TUTORIAL:0 "教程"
 SETTING_REACTIVE_TUTORIAL:0 "显示响应式建议"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\n设置是否在游戏过程中针对性地显示教程。对《十字军之王3》的新玩家非常有用。"
 SETTING_SHOW_SUGGESTIONS:0 "显示建议"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:0 "#T $SETTING_SHOW_SUGGESTIONS$#!\n设置游戏是否进行常规操作提示。对《十字军之王3》的新玩家非常有用。"
 RESET_REACTIVE_ADVICE:0 "重置响应式建议"
 RESET_REACTIVE_ADVICE_TOOLTIP:0 "#T 重置响应式建议#!\n之前看过的响应式建议将会再次显示一次。"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "重置响应式建议"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "你确定要重置响应式建议吗？"
 SETTING_ADVANCED_SHADERS:0 "高级着色器效果"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T 高级着色器效果\n#!此选项启用高级着色器效果。\n\n关闭可以提升性能，但会牺牲某些特效（例如地形和水域）"
 BASED_ON_ZOOM_LEVEL:0 "动态"
 ALWAYS_HIDE:0 "总是隐藏"
 ALWAYS_SHOW:0 "总是显示"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "海岸线"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\n此选项控制领地海岸线何时显示。\n$BASED_ON_ZOOM_LEVEL$下，海岸线将在细节缩放级别时隐藏。\n\n选择$ALWAYS_SHOW$或$ALWAYS_HIDE$可能提升性能，但会让领地海岸线无法自动隐藏。"
 
