l_french:
 SETTING_AUTOSAVE:0 "Intervalle de sauvegarde automatique"
 SETTING_DEBUG_SAVES:0 "Nombre de sauvegardes de débogage"
 SETTING_TUTORIAL:0 "Didacticiel"
 SETTING_DISABLED_HINTS:0 "Conseils désactivés"
 SETTING_FOCUS_ON_COMBAT:0 "Centrer sur le combat"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "Frontières du pays sur les côtes"
 SETTING_TOOLTIP_DELAY:1 "Délai de l'infobulle"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_TOOLTIP_DELAY$#!\nDéfinit le délai avant l'apparition des infobulles."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Délai de déverrouillage"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDéfinit le délai avant que les infobulles soient déverrouillées."
 SETTING_TOOLTIP_LOCK_TIME:0 "Délai de verrouillage"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDéfinit le délai avant le verrouillage des infobulles."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Délai de verrouillage si ouvert"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDéfinit le délai avant le verrouillage des infobulles lorsqu'une autre infobulle est déjà ouverte."
 # Audio
 SETTING_Sound_Effects:1 "Tous les effets sonores"
 SETTING_Sound_Effects_TOOLTIP:0 "#T Volume des effets sonores\n#!Règle le volume de tous les effets sonores."
 SETTING_Ambience:0 "Ambiance"
 SETTING_Ambience_TOOLTIP:1 "#T Volume d'ambiance\n#!Règle le volume des sons d'ambiance."
 SETTING_TOOLTIP_MODE:1 "Mode infobulle"
 SETTING_TOOLTIP_MODE_TOOLTIP:2 "#T $SETTING_TOOLTIP_MODE$#!\nDéfinit la façon dont les infobulles « se verrouillent » et activent les infobulles dans les infobulles."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Selon la souris"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nLes infobulles sont automatiquement verrouillées jusqu'à ce que le curseur s'éloigne."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Selon l'action"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nAppuyer sur le #V bouton du milieu de la souris#! pour verrouiller ou déverrouiller les infobulles."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Selon le temps"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nLes infobulles sont verrouillées si le curseur ne bouge pas pendant un court instant. #weak (Paramètre par défaut)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Divers"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Infobulles"
 SETTINGS_CATEGORY_SFX:0 "Effets sonores spécifiques"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Général"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Contrôles de carte"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Sauvegardes"
 SETTINGS_CATEGORY_LANGUAGE:0 "Langue"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avancé"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portraits"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Afficher les graphismes des maladies et blessures"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nDéfinit si les graphismes des maladies et blessures sont visibles sur les portraits des personnages."
 NEVER:0 "Jamais"
 MONTHLY:0 "Chaque mois"
 HALFYEAR:0 "Tous les 6 mois"
 YEARLY:0 "Chaque année"
 FIVE_YEAR:0 "Tous les 5 ans"
 SETTINGS_CATEGORY_TUTORIAL:0 "Didacticiel"
 SETTING_REACTIVE_TUTORIAL:1 "Afficher les conseils personnalisés"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nDétermine si le jeu doit afficher des conseils qui réagissent à la façon dont vous jouez. Utile pour les nouveaux joueurs de Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Afficher les suggestions"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nDéfinit si le jeu doit régulièrement suggérer des choses à faire. C'est utile pour les joueurs découvrant Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Réinitialiser les conseils personnalisés"
 RESET_REACTIVE_ADVICE_TOOLTIP:0 "#T Réinitialiser les conseils personnalisés#!\nLes conseils personnalisés vus précédemment réapparaîtront."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Réinitialiser les conseils personnalisés"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Voulez-vous vraiment réinitialiser les conseils personnalisés ?"
 SETTING_ADVANCED_SHADERS:0 "Effets de nuanceur avancés"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Effets de nuanceur avancés\n#!Cette option permettra des effets de nuanceur avancés.\n\nLe fait de le désactiver peut augmenter les performances au risque d'aggraver la qualité de certains effets (par exemple, le terrain et l'eau)"
 BASED_ON_ZOOM_LEVEL:0 "Dynamique"
 ALWAYS_HIDE:0 "Toujours masquer"
 ALWAYS_SHOW:0 "Toujours afficher"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Frontières côtières"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nCette option permettra de contrôler à quel moment les frontières des pays côtiers doivent être indiquées.\nSi $BASED_ON_ZOOM_LEVEL$ alors elles seront masquées au niveau de zoom détaillé.\n\nChoisir $ALWAYS_SHOW$ ou $ALWAYS_HIDE$ peut augmenter les performances, mais les frontières des pays côtiers ne se masquent plus dynamiquement."
 
