l_spanish:
 SETTING_AUTOSAVE:0 "Frecuencia de autoguardado"
 SETTING_DEBUG_SAVES:0 "Depuraciones guardadas"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "Pistas desactivadas"
 SETTING_FOCUS_ON_COMBAT:0 "Centrar en combate"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "Fronteras del señorío en costas"
 SETTING_TOOLTIP_DELAY:1 "Retardo herramientas"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nEstablece la pausa para la ayuda emergente."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Retardo de desbloqueo"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nEstablece la pausa para desbloquear la ayuda emergente."
 SETTING_TOOLTIP_LOCK_TIME:0 "Retardo bloqueo"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nEstablece la pausa para bloquear la ayuda emergente."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Retardo bloqueo abierto"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nEstablece la pausa para bloquear la ayuda emergente cuando ya se está mostrando otra ayuda."
 # Audio
 SETTING_Sound_Effects:1 "Todos los efectos de sonido"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Volumen de efectos\n#!Establece el volumen de TODOS los efectos de sonido."
 SETTING_Ambience:0 "Ambiente"
 SETTING_Ambience_TOOLTIP:1 "#T Volumen de ambiente\n#!Establece el volumen de los sonidos ambientales."
 SETTING_TOOLTIP_MODE:1 "Modo herramienta"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nEstablece la forma en que se "bloquea" la ayuda emergente, lo que permite consultar ayudas sobre temas dentro de dicha ayuda."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Tendencia del ratón"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nLa ayuda emergente se bloquea hasta que apartes el cursor."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Bloqueo de acción"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPulsa el #V botón central del ratón#! para bloquear y desbloquear la ayuda emergente."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Pausa temporal"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nLa ayuda emergente se queda fija si no mueves el cursor durante un breve plazo. #weak (opción predeterminada.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Varios"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Herramientas"
 SETTINGS_CATEGORY_SFX:0 "Efectos de sonido específicos"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "General"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controles de juego"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Partidas guardadas"
 SETTINGS_CATEGORY_LANGUAGE:0 "Lenguaje"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avanzados"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Retratos"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Mostrar gráficamente las enfermedades y heridas"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nEstablece si mostrar enfermedades y heridas gráficamente en los retratos de personajes."
 NEVER:0 "Nunca"
 MONTHLY:0 "Cada mes"
 HALFYEAR:0 "Cada 6 meses"
 YEARLY:0 "Cada año"
 FIVE_YEAR:0 "Cada 5 años"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Mostrar consejos reactivos"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nEstablece si el juego debe mostrar consejos de tutorial según se juega. Úes útil para los nuevos jugadores de Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Mostrar sugerencias"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nEstablece si el juego te sugiere actividades a intervalos regulares. Útil para aquellos jugadores que estén descubriendo Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Reiniciar consejos reactivos"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Reiniciar consejos reactivos#!\nSe volverán a mostrar los consejos reactivos que hayas visto antes."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Reiniciar consejos reactivos"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "¿De verdad quieres reiniciar los consejos reactivos?"
 SETTING_ADVANCED_SHADERS:0 "Efectos de sombreado avanzados"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Efectos de sombreado avanzados\n#!Esta opción activará los efectos de sombreado avanzados.\n\nSi los desactivas, puede mejorar el rendimiento, pero ciertos efectos se verán peor, como el terreno o el agua"
 BASED_ON_ZOOM_LEVEL:0 "Dinámico"
 ALWAYS_HIDE:0 "Ocultar siempre"
 ALWAYS_SHOW:0 "Mostrar siempre"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Fronteras costeras"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nCon esta opción se determina si se mostrarán o no las fronteras costeras.\nSi eliges $BASED_ON_ZOOM_LEVEL$, se ocultarán cuando acerques la imagen en detalle.\n\nSi eliges $ALWAYS_SHOW$ o $ALWAYS_HIDE$, puede mejorar el rendimiento pero las fronteras costeras del señorío no se mostrarán y ocultarán automáticamente."
 
